# Lists of first and last names for masking
first_names = [
    "Emma",
    "Liam",
    "Olivia",
    "Noah",
    "Ava",
    "Sophia",
    "Isabella",
    "Mia",
    "Charlotte",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Emily",
    "Elizabeth",
    "Mila",
    "Ella",
    "Avery",
    "Sofia",
    "Camila",
    "Jackson",
    "Aiden",
    "Lucas",
    "Liam",
    "Noah",
    "Ethan",
    "Caden",
    "Logan",
    "Mason",
    "Oliver",
    "Elijah",
    "Grayson",
    "Jacob",
    "Michael",
    "Benjamin",
    "Carter",
    "Alexander",
    "James",
    "Jayden",
    "John",
    "Matthew",
    "David",
    "Joseph",
    "Daniel",
    "Henry",
    "Owen",
    "Wyatt",
    "Dylan",
    "Gabriel",
    "William",
    "Nathan",
    "Samuel",
    "Andrew",
    "Jack",
    "Anthony",
    "Christopher",
    "Joshua",
    "Jaxon",
    "Emily",
    "Chloe",
    "Grace",
    "Zoe",
    "Nora",
    "Hannah",
    "Lily",
    "Addison",
    "Aubrey",
    "Zoey",
    "Elizabeth",
    "Ella",
    "Mila",
    "Scarlett",
    "Victoria",
    "Lillian",
    "Camilla",
    "Layla",
    "Penelope",
    "Riley",
    "Aria",
    "Eleanor",
    "Hazel",
    "Aurora",
    "Lucy",
    "Audrey",
    "Bella",
    "Savannah",
    "Claire",
]

last_names = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Mitchell",
    "Carter",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
    "Murphy",
    "Bailey",
    "Cooper",
    "Richardson",
]

org_names = [
    "Acme Corporation",
    "Apex Industries",
    "BlueSky Ventures",
    "Cascade Solutions",
    "Crimson Enterprises",
    "DynaTech Systems",
    "Elite Innovations",
    "Evergreen Holdings",
    "Fusion Technologies",
    "Global Solutions Inc.",
    "Harmony Enterprises",
    "Infinite Dynamics",
    "Jupiter Enterprises",
    "Luminous Group",
    "Momentum Solutions",
    "Nimbus Corporation",
    "Omega Industries",
    "Pantheon Innovations",
    "Quantum Ventures",
    "Radiant Technologies",
    "Solaris Systems",
    "TerraFirm Enterprises",
    "United Synergy",
    "Vanguard Corporation",
    "Zenith Industries",
    "AstraTech Solutions",
    "Blaze Technologies",
    "Celestial Holdings",
    "Delta Dynamics",
    "Eclipse Innovations",
    "Flux Corporation",
    "Galaxy Enterprises",
    "Helios Group",
    "Innovare Solutions",
    "Jade Industries",
    "Lunar Systems",
    "MegaByte Ventures",
    "NovaTech Corporation",
    "Optima Innovations",
    "Penta Solutions",
    "Quantex Enterprises",
    "Radiant Innovations",
    "Solstice Corporation",
    "TerraNova Holdings",
    "Universal Synergy",
    "Visionary Technologies",
    "Zephyr Group",
    "Aeon Solutions",
    "Bliss Enterprises",
    "Celestial Technologies",
    "Dynamo Corporation",
    "Elysium Innovations",
]

org_structure = ["inc.", "ltd.", "gmbh"]
